package commands.extra

import data.Coordinates
import data.FuelType
import data.Vehicle
import data.VehicleType
import managers.CollectionManager
import org.koin.java.KoinJavaComponent.inject
import java.time.ZonedDateTime
import kotlin.random.Random

class ItemBuilder() {
    // todo: к enum-ам обращаться в том числе по числу. Можно использовать ordinal
    val collectionManager: CollectionManager by inject()

    fun autoAdd(): Vehicle { // todo: сделать фабричный метод??
        // todo: делать что-то с magic numbers??
       val id = collectionManager.getCollectionSize()
        val name = "Autogenerated item"
        val coordinates = Coordinates(Random.nextInt(-88, Int.MAX_VALUE), Random.nextFloat() * 484)
        val creationDate = ZonedDateTime.now()
        val enginePower = Random.nextDouble() * Double.MAX_VALUE
        val fuelConsumption = Random.nextInt(1, Int.MAX_VALUE)
        val type = VehicleType.entries.toTypedArray().random()
        val fuelType = FuelType.entries.toTypedArray().random()
        return Vehicle(id, name, coordinates, creationDate, enginePower, fuelConsumption, type, fuelType)
    }

}