package commands.extra

import data.Coordinates
import data.FuelType
import data.Vehicle
import data.VehicleType
import kotlin.random.Random

interface Autogeneratable {

    /**
     * Checks if the given flag is "--auto".
     *
     * @param flag the flag to check
     * @return true if the flag is "--auto", false otherwise
     */
    fun checkFlag(flag: String): Boolean {
        return flag == "--auto"
    }

    /**
     * Automatically generates a valid item for Vehicle collection
     */
    fun autoAdd(): Vehicle {
        val name = "Autogenerated item"
        val coordinates = Coordinates(Random.nextInt(-88, Int.MAX_VALUE), Random.nextFloat() * 484)
        val enginePower = Random.nextDouble() * Double.MAX_VALUE
        val fuelConsumption = Random.nextInt(1, Int.MAX_VALUE)
        val type = VehicleType.entries.toTypedArray().random()
        val fuelType = FuelType.entries.toTypedArray().random()
        return Vehicle(
            name = name,
            coordinates = coordinates,
            enginePower = enginePower,
            fuelConsumption = fuelConsumption,
            type = type,
            fuelType = fuelType
        )
    }
}